source 'https://github.com/CocoaPods/Specs.git'


target :MendeleyKitiOSTests do
	platform :ios, '9.0'
    pod 'OCMock'
end

target :MendeleyKitOSXTests do
	platform :osx, '10.9'
    pod 'OCMock'
end
