source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target :MendeleyKitTests, :exclusive => true  do
    pod 'OCMock'
end

target :MendeleyKitiOSTests, :exclusive => true do
    pod 'OCMock'
end

