source 'https://github.com/CocoaPods/Specs.git'

target :MendeleyKitTests  do
    pod 'OCMock'
end

target :MendeleyKitiOSTests do
	platform :ios, '8.0'
    pod 'OCMock'
end

target :MendeleyKitOSXTests do
	platform :osx, '10.9'
    pod 'OCMock'
end
